apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  database-password: bXlzcWxwYXNzd29yZA==
  database-user: bXlzcWx1c2Vy
  api-password: cGFzc3dvcmQ=
  database-root-password: cm9vdHBhc3N3b3Jk